# Generated by Django 5.0.3 on 2024-03-09 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user'], name='api_portfol_user_id_e5189f_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['symbol'], name='api_portfol_symbol_914efe_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpurchase',
            index=models.Index(fields=['user', 'trade_date'], name='api_stockpu_user_id_5c9d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpurchase',
            index=models.Index(fields=['stock'], name='api_stockpu_stock_6a5b34_idx'),
        ),
    ]
